default: &default
  adapter: redis
  url:  <%= ENV.fetch("REDIS_#{Rails.env}_URL") { "redis://localhost:6379/redis/#{Rails.env}/cable" } %>
  channel_prefix: mahaga

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
