development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/gamebase/development" } %>
  channel_prefix: gamebase

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/gamebase/test" } %>
  channel_prefix: gamebase

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/gamebase/production" } %>
  channel_prefix: gamebase
